#!/bin/bash

## Unit tests for the .githooks/VERSIONS marker and the version probes that
## decide whether a generated part is regenerated, in scripts/init.sh
## See https://github.com/NaanProphet/git-logic-init/issues/20
##
## To run tests, simply run `bash versions-marker.sh.t` from this folder.
## Output is TAP-ish; exits non-zero if any assertion fails.
##
## Everything here runs against throwaway folders under mktemp -- no real repo
## and no git-lfs are needed, so this runs unchanged on CI.

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# source init.sh for its functions only, without running the installer
SOURCE_FUNCTIONS_ONLY=true
# shellcheck source=../scripts/init.sh
. "${DIR}/../scripts/init.sh"
unset SOURCE_FUNCTIONS_ONLY

count=0
failed=0

function ok () {
  local description=$1
  count=$((count+1))
  echo "ok ${count} - ${description}"
}

function not_ok () {
  local description=$1
  count=$((count+1))
  failed=$((failed+1))
  echo "not ok ${count} - ${description}"
}

function is () {
  local actual=$1
  local expected=$2
  local description=$3

  if [ "$actual" = "$expected" ]; then
    ok "${description}"
  else
    not_ok "${description} (expected '${expected}', got '${actual}')"
  fi
}

function isnt () {
  local actual=$1
  local unexpected=$2
  local description=$3

  if [ "$actual" != "$unexpected" ]; then
    ok "${description}"
  else
    not_ok "${description} (got the unwanted '${unexpected}')"
  fi
}

function file_missing () {
  local path=$1
  local description=$2

  if [ -e "${path}" ]; then
    not_ok "${description} (unexpectedly present: ${path})"
  else
    ok "${description}"
  fi
}

WORK="$(mktemp -d)"
trap 'rm -rf "${WORK}"' EXIT

## ---------------------
## read_marker. A repo predating the marker file, or a key a newer init.sh has
## not written yet, has to read as "0" -- compareVersions expands that to
## 0.0.0.0, so the part regenerates exactly once and is stable thereafter.
## ---------------------
echo "# a missing file, key or value reads as 0"

is "$(read_marker "${WORK}/nonexistent" "${KEY_LFS}")" "0" "an absent marker file reads as 0"

MARKER="${WORK}/VERSIONS"
cat > "${MARKER}" <<'EOF'
# Managed by git-logic-init -- regenerated by init.sh, do not edit.

git-lfs=3.6.1
git-store-meta=v2.0.1+sha256.abcdef012345
EOF

is "$(read_marker "${MARKER}" "${KEY_SELF}")" "0" "an absent key reads as 0"
is "$(read_marker "${MARKER}" "${KEY_LFS}")" "3.6.1" "a present key reads its value"
is "$(read_marker "${MARKER}" "${KEY_META}")" "v2.0.1+sha256.abcdef012345" \
  "a value containing + and . survives intact"

printf 'git-lfs=\n' > "${WORK}/empty-value"
is "$(read_marker "${WORK}/empty-value" "${KEY_LFS}")" "0" "an empty value reads as 0"

## ---------------------
## Key matching is anchored, so one key cannot be read out of another. Nothing
## shares a prefix today, but a future key easily could.
## ---------------------
echo "# keys are matched whole, not as prefixes"

cat > "${WORK}/prefixes" <<'EOF'
git-lfs-extra=9.9.9
git-lfs=3.6.1
EOF
is "$(read_marker "${WORK}/prefixes" "${KEY_LFS}")" "3.6.1" \
  "a longer key sharing the prefix is not mistaken for this one"

## ---------------------
## The file is committed, so it is somebody else's content as far as this script
## is concerned. grep/cut, never `source` -- sourcing would execute it.
## ---------------------
echo "# the marker file is parsed, never executed"

cat > "${WORK}/hostile" <<EOF
git-lfs=3.6.1
\$(touch "${WORK}/pwned")
\`touch "${WORK}/pwned-backtick"\`
EOF
is "$(read_marker "${WORK}/hostile" "${KEY_LFS}")" "3.6.1" "a hostile file still parses"
file_missing "${WORK}/pwned" "command substitution in the file does not run"
file_missing "${WORK}/pwned-backtick" "backticks in the file do not run"

## ---------------------
## write_markers has to be byte-identical run to run, or re-running init.sh
## dirties the working tree all by itself -- which is the whole point.
## ---------------------
echo "# writing the marker is idempotent and round-trips"

OUT="${WORK}/written"
write_markers "${OUT}" "3.7.0" "v2.0.1+sha256.abcdef012345" "v0.2.0"
is "$?" "0" "writing the marker succeeds"
FIRST="$(cksum < "${OUT}")"
write_markers "${OUT}" "3.7.0" "v2.0.1+sha256.abcdef012345" "v0.2.0"
is "$(cksum < "${OUT}")" "${FIRST}" "the file is byte-identical on the second write"

is "$(read_marker "${OUT}" "${KEY_LFS}")" "3.7.0" "git-lfs round-trips"
is "$(read_marker "${OUT}" "${KEY_META}")" "v2.0.1+sha256.abcdef012345" "git-store-meta round-trips"
is "$(read_marker "${OUT}" "${KEY_SELF}")" "v0.2.0" "git-logic-init round-trips"

file_missing "${OUT}.tmp" "no temp file is left behind"

## ---------------------
## An older init.sh must not drop a key a newer one added, or the two would
## take turns rewriting the file -- a fresh oscillation in place of the one
## this ticket removes.
## ---------------------
echo "# an unrecognized key survives a rewrite"

printf 'future-tool=1.2.3\n' >> "${OUT}"
write_markers "${OUT}" "3.7.0" "v2.0.1+sha256.abcdef012345" "v0.2.0"
is "$(read_marker "${OUT}" "future-tool")" "1.2.3" "a key this version knows nothing about is preserved"
is "$(grep -c '^git-lfs=' "${OUT}")" "1" "a known key is not duplicated on rewrite"

## ---------------------
## parse_lfs_version. `git lfs version` prints the build details in
## parentheses, and those differ between Homebrew and MacPorts -- so the match
## is anchored on the git-lfs/ prefix. A bare "first digits" match would return
## the Go version instead, silently comparing the wrong number.
## ---------------------
echo "# the git-lfs version is read from the git-lfs/ prefix, not the Go version"

is "$(parse_lfs_version 'git-lfs/3.7.0 (GitHub; darwin arm64; go 1.24.4)')" "3.7.0" \
  "a current Homebrew build parses"
is "$(parse_lfs_version 'git-lfs/2.13.3 (GitHub; darwin amd64; go 1.16)')" "2.13.3" \
  "an older build parses"
is "$(parse_lfs_version 'git-lfs/3.4.0')" "3.4.0" "a bare version with no build details parses"
is "$(parse_lfs_version 'git-lfs/3.6.1.2 (GitHub; linux amd64; go 1.22)')" "3.6.1.2" \
  "a four-component version parses"

isnt "$(parse_lfs_version 'git-lfs/3.7.0 (GitHub; darwin arm64; go 1.24.4)')" "1.24.4" \
  "the Go version is never returned"

is "$(parse_lfs_version 'some other tool 1.2.3')" "" "an unrecognized line yields nothing"
is "$(parse_lfs_version '')" "" "empty input yields nothing"
is "$(parse_lfs_version 'git-lfs/notaversion')" "" "a non-numeric version yields nothing"

## ---------------------
## An unparsable version has to leave the committed hooks alone. This is the
## branch init.sh takes when it cannot read `git lfs version` at all.
## ---------------------
echo "# an unparsable version compares as older, so nothing regenerates"

is "$(compareVersions "$(parse_lfs_version 'garbage')" "3.6.1")" "-1" \
  "nothing parsed compares as older than any recorded version"

## ---------------------
## store_meta_version. TAG_COMMIT lives in bootstrap.sh, and neither bumping it
## within an upstream tag nor changing dst-hack.patch moves --version -- so the
## identity has to include a digest of the file itself.
## ---------------------
echo "# git-store-meta is identified by version plus a labelled digest"

STUB="${WORK}/git-store-meta.pl"
printf '#!/bin/sh\necho v2.0.1\n' > "${STUB}"
chmod a+x "${STUB}"

META="$(store_meta_version "${STUB}")"
case "${META}" in
  v2.0.1+sha256.*) ok "the identity is <version>+sha256.<digest> (${META})" ;;
  *) not_ok "the identity is <version>+sha256.<digest> (got '${META}')" ;;
esac

DIGEST="${META#v2.0.1+sha256.}"
is "${#DIGEST}" "12" "the digest is truncated to 12 hex characters"

# the case the digest exists for: same --version, different file
printf '#!/bin/sh\n# a TAG_COMMIT bump\necho v2.0.1\n' > "${STUB}"
chmod a+x "${STUB}"
CHANGED="$(store_meta_version "${STUB}")"
isnt "${CHANGED}" "${META}" "changing the file changes the identity even when --version does not"

is "$(store_meta_version "${WORK}/no-such-script")" "" "a missing script yields nothing"

printf '#!/bin/sh\nexit 1\n' > "${WORK}/broken.pl"
chmod a+x "${WORK}/broken.pl"
is "$(store_meta_version "${WORK}/broken.pl")" "" "a script that prints no version yields nothing"

## ---------------------
## parts_present. An up-to-date marker whose parts have been deleted would
## otherwise leave the repo permanently without hooks.
## ---------------------
echo "# a missing part is detected regardless of the marker"

HOOKS="${WORK}/hooks"
mkdir -p "${HOOKS}/post-checkout.d"
if parts_present "${HOOKS}" "${LFS_PART}"; then
  not_ok "an empty .d folder reports no part"
else
  ok "an empty .d folder reports no part"
fi

printf '#!/bin/sh\n' > "${HOOKS}/post-checkout.d/${LFS_PART}"
if parts_present "${HOOKS}" "${LFS_PART}"; then
  ok "a present part is found"
else
  not_ok "a present part is found"
fi

if parts_present "${HOOKS}" "${META_PART}"; then
  not_ok "a different part is not mistaken for this one"
else
  ok "a different part is not mistaken for this one"
fi

mkdir -p "${WORK}/no-hooks"
if parts_present "${WORK}/no-hooks" "${LFS_PART}"; then
  not_ok "a folder with no .d subfolders at all reports no part"
else
  ok "a folder with no .d subfolders at all reports no part"
fi

## ---------------------
## The gate itself, in the form init.sh applies it: only a strictly newer
## git-lfs rewrites the part, so a mixed-version team stops oscillating the
## tracked hooks and the newest machine's output propagates to everyone.
## ---------------------
echo "# only a strictly newer git-lfs regenerates"

function lfs_gate () {
  local local_version=$1
  local marker_version=$2
  local expected=$3
  local verdict='leaves it alone'

  if [ "$(compareVersions "${local_version}" "${marker_version}")" -eq 1 ]; then
    verdict='regenerates'
  fi
  is "${verdict}" "${expected}" "local ${local_version} against marker ${marker_version} ${expected}"
}

lfs_gate "3.7.0" "3.6.1" "regenerates"
lfs_gate "3.6.1" "3.7.0" "leaves it alone"
lfs_gate "3.7.0" "3.7.0" "leaves it alone"
lfs_gate "3.7.0" "0" "regenerates"
lfs_gate "3.10.0" "3.9.0" "regenerates"

## ---------------------
## git-store-meta compares for equality, not order: its identity ends in a hash
## and a hash has no ordering. Any difference regenerates.
## ---------------------
echo "# git-store-meta regenerates on any difference"

function meta_gate () {
  local local_version=$1
  local marker_version=$2
  local expected=$3
  local verdict='leaves it alone'

  if [ "${local_version}" != "${marker_version}" ]; then
    verdict='regenerates'
  fi
  is "${verdict}" "${expected}" "local '${local_version}' against marker '${marker_version}' ${expected}"
}

meta_gate "v2.0.1+sha256.aaaaaaaaaaaa" "v2.0.1+sha256.aaaaaaaaaaaa" "leaves it alone"
meta_gate "v2.0.1+sha256.bbbbbbbbbbbb" "v2.0.1+sha256.aaaaaaaaaaaa" "regenerates"
meta_gate "v2.0.1+sha256.aaaaaaaaaaaa" "0" "regenerates"

## ---------------------
## The stale-init.sh guard. RELEASE_VERSION carries a leading v, which
## compareVersions cannot parse, so both sides are stripped first.
## ---------------------
echo "# an init.sh older than the marker is refused"

function self_gate () {
  local script_version=$1
  local marker_version=$2
  local expected=$3
  local verdict='runs'

  if [ "$(compareVersions "${script_version#v}" "${marker_version#v}")" -eq -1 ]; then
    verdict='refuses'
  fi
  is "${verdict}" "${expected}" "init.sh ${script_version} against marker ${marker_version} ${expected}"
}

self_gate "v0.2.0" "v0.2.0" "runs"
self_gate "v0.2.1" "v0.2.0" "runs"
self_gate "v0.2.0" "v0.2.1" "refuses"
self_gate "v0.2.0" "v0.10.0" "refuses"
self_gate "v0.2.0" "0" "runs"
self_gate "v0.1.15" "v0.2.0" "refuses"

## ---------------------
## The version this release records, so a botched bump is caught here rather
## than by every consumer at once.
## ---------------------
echo "# RELEASE_VERSION is well formed"

case "${RELEASE_VERSION}" in
  v[0-9]*.[0-9]*.[0-9]*) ok "RELEASE_VERSION is a v-prefixed three-part version (${RELEASE_VERSION})" ;;
  *) not_ok "RELEASE_VERSION is a v-prefixed three-part version (got '${RELEASE_VERSION}')" ;;
esac

## ---------------------
## Generated files carry an ownership comment, so a hook clobbered by
## `git lfs install --force` is recognizable as having been ours.
## ---------------------
echo "# generated files are stamped just after the shebang"

printf '#!/bin/sh\ncommand -v git-lfs >/dev/null 2>&1 || exit 2\ngit lfs post-checkout "$@"\n' \
  > "${WORK}/generated"
stamp_managed_by "${WORK}/generated" "${WORK}/stamped"
is "$?" "0" "stamping succeeds"
is "$(sed -n 1p "${WORK}/stamped")" "#!/bin/sh" "the shebang stays on line 1"
is "$(sed -n 2p "${WORK}/stamped")" "${MANAGED_BY}" "the note is inserted on line 2"
is "$(sed -n 4p "${WORK}/stamped")" 'git lfs post-checkout "$@"' "the rest of the file is unchanged"
is "$(wc -l < "${WORK}/stamped" | tr -d ' ')" "4" "exactly one line is added"

## ---------------------
echo "1..${count}"
if [ "$failed" -gt 0 ]; then
  echo "# FAILED ${failed} of ${count} tests"
  exit 1
fi
echo "# passed ${count} tests"
