language: bash
before_script:
  - "./scripts/bootstrap.sh"
  - "./test/download.sh"
script:
  - cd ./test && perl dst-hack.t; cd -
before_deploy:
  - cd scripts
  - sha256sum "init.sh" > "init.sh.sha256"
  - sha256sum "git-store-meta.pl" > "git-store-meta.pl.sha256"
  - cd ..
deploy:
  provider: releases
  api_key:
    secure: pET2z6Jvhy1hPtYU2yVUN4lO9rcF0Q7QsM32CEqdlJQqtBa6Vw7nXnoI39laAJCcwI1RrYvrmA1wk7r7nydwCnCEb8gp1zL1DPsBbSK6iLessUMoRd+QuRImWkwjVdHvuC360J5Po+4tnbVDpkigO6NRcrtHSRVb0ZDkQoAzzPyeWLQX+eggkFyWNjxrUY4IMTI5f+wlQJiTsbsKnQCyKJtogplOfv7cZ+2OidLlY6hUX2yM5CtODBAsJogV//uH7C4OMNvxqH3hVxT7IwQHAJauLv2mK4pYGp9dhb7iFRFu/215pdgaugDPVoUQD4e83qK84+jCNdlI8TVOneQys3Vke8U53VEwx1XVUIigpCLjQzg6dgGpWEwLZ+PwJLHUC5+jGtldokC3lhmG3gLlnam9aHssnv5iI7GaYXz5QSR7e183mdFPC5tufnv8a6L6DOFOeFt763ZjL5V08kyRUuIH5skc/6MLGHbqq3aMz0209lv74JUmpZTWEcRmj1WfRsZiClfAZ1ua6HPGiIlVFJy2rCOXqh2zUd3r3Q286YNKonhs2nRyGwfadNbdz4zey53rTv46CqDxKdKNDStW+ZEtKTYd9xd3iiQyIlXbVV8aj/AsA7JIvqd9XPfNewNFMAySqiZq6mylEv/2tg7/1VUdZsezC33nSCoXuw0ZrmI=
  file: 
    - scripts/init.sh
    - scripts/init.sh.sha256
    - scripts/git-store-meta.pl
    - scripts/git-store-meta.pl.sha256
  on:
    repo: NaanProphet/git-logic-init
  skip_cleanup: 'true'
  draft: true
  overwite: true
