#!/bin/bash

### This script is used to bootstrap a blank Apple Logic repo with the
### required Git commit hooks for Git LFS and Git Store Meta.
### It stores the hooks in a custom Hooks location called .githooks
### which can then be committed into source control.
###
### If the .githooks folder is already present, then this script
### bypasses bootstrapping and simply re-initializes the .githooks
### folder. This is required after each new clone.
###
### See https://github.com/danny0838/git-store-meta for more info about
### how file timestamps are preserved with commit hooks.
###
### Platform: Mac OS X
### Dependencies: Git (>= 2.9), Git LFS, Git Store Meta
### Recommended: Homebrew or MacPorts, to install the above
###
### Development notes:
### - Re-running the script is idempotent: each generated part is only rewritten
###   when the tool that produces it is newer than the version recorded in
###   .githooks/VERSIONS, and the dispatchers are byte-identical run to run.
### - To start over, remove all temp files using: `rm -rf .git*`
###
### Author: Krishna Bhamidipati (NaanProphet)
### version: 0.2.0
###

RELEASE_VERSION="v0.2.0"
RELEASE_BASEURL="https://github.com/NaanProphet/git-logic-init/releases/download"
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
LFS_TYPES=(
  '*.wav' '*.aif' '*.aiff' '*.mp3' '*.m4a' '*.alac' '*.aifc' '*.au'
  '*.zip' '*.gz' '*.tgz'
  'ProjectData'
)
# loosely based on https://sound.stackexchange.com/a/38454
GIT_IGNORE=(
  '.DS_Store'
  'Freeze Files'
  'Undo Data.nosync'
  'Project File Backups'
  'Autosave'
  '*.rxdoc'
  'Undo Data'
)
GIT_META_FIELDS="file,type,mtime"
NEW_HOOKS_DIR=".githooks"
# Git runs exactly one file per event, so each hook is a generated dispatcher
# that runs every executable part in a sibling <hookname>.d folder, in sort
# order. The prefixes below are sort order, not priority: LFS has to restore
# file contents before Git Store Meta stamps the timestamps back on. Two
# digits, with gaps, so parts can be slotted in between later.
LFS_PART="10-git-lfs"
META_PART="20-git-store-meta"
# Committed marker recording which version of each tool wrote which part, so a
# part is only regenerated by a machine whose copy of that tool is newer than
# whatever last wrote it. Has to be committed -- local git config is not cloned,
# and the value has to travel with the repo. Safe to keep in .githooks: Git only
# executes files whose name matches a hook exactly. Non-dot so it is visible to
# anyone who opens the folder, since it is the file that explains why the hooks
# did or did not change. See issue #20.
VERSIONS_FILE="VERSIONS"
KEY_LFS="git-lfs"
KEY_META="git-store-meta"
KEY_SELF="git-logic-init"
# Every generated file carries this, so that a hook clobbered by something else
# (`git lfs install --force`, say) is recognizable as ours.
MANAGED_BY="# Managed by git-logic-init -- regenerated by init.sh, do not edit."
# One-time copy of the old single-file merged hooks, so hand edits are
# recoverable. Safe to delete once the new hooks are known to work.
MIGRATION_DIR="pre-migration"
MIN_GIT_VERSION="2.9"
# uncomment the line below to enable DEBUG logging
#DEBUG=true

# -----------------------------------------------------------------------------

# Compares two dot-separated version strings, writing the verdict to stdout 
# (NOT the exit status):
#
#   -1 if $1 <  $2
#    0 if $1 == $2
#    1 if $1 >  $2
#
# Compares up to four numeric components; components absent from the shorter
# string expand to 0, so "2.9", "2.9.0" and "2.9.0.0" all compare equal. The
# 10# prefix forces base 10 so a zero-padded component (2.09) is not read as
# octal, and makes an empty/unparsed version compare as 0.0.0.0.
#
# Initial thanks to: https://stackoverflow.com/a/3511118/1603489
function compareVersions () {
  typeset    IFS='.'
  typeset -a v1=( $1 )
  typeset -a v2=( $2 )
  typeset    n diff

  for (( n=0; n<4; n+=1 )); do
    diff=$(( 10#0${v1[n]} - 10#0${v2[n]} ))
    if [ $diff -ne 0 ] ; then
      [ $diff -lt 0 ] && echo '-1' || echo '1'
      return
    fi
  done
  echo '0'
}

# All user-facing messages go through these three helpers. printf expands \033
# identically whether bash is in POSIX/sh mode or not, unlike the echo builtin, whose
# escape handling depends on the xpg_echo flag Apple enables only in sh mode -- so
# `bash init.sh` and `./init.sh` used to print a literal \033[31m. See issue #15.
#
# The message is passed as a %s argument, so a % in a path or filename is never read
# as a format specifier.
function err () {
  printf >&2 '\033[31m %s \033[0m\n' "$1"
}

function warn () {
  printf >&2 '\033[33m %s \033[0m\n' "$1"
}

function info () {
  printf >&2 '\033[32m %s \033[0m\n' "$1"
}

# Echoes the package manager present on this machine: "brew", "port", or nothing
# at all. Homebrew wins when both are installed, since its install needs no sudo.
# The script never calls either one -- this only decides whether to warn that
# dependencies may have to be installed by hand.
function detect_pkg_manager () {
  if [ -x "$(command -v brew)" ]; then
    echo 'brew'
  elif [ -x "$(command -v port)" ]; then
    echo 'port'
  fi
}

# Reads one key out of the committed marker file, echoing "0" when the file, the
# key, or its value is missing -- so an unmarked repo compares as 0.0.0.0 and
# regenerates exactly once, which is the migration path for repos that predate
# the file.
#
# grep/cut, never `source`: this is a committed file, and sourcing it would
# execute whatever happened to be in it.
function read_marker () {
  local file=$1
  local key=$2
  local value

  [ -f "${file}" ] || { echo '0'; return; }
  value="$(grep "^${key}=" "${file}" | head -1 | cut -d'=' -f2-)"
  [ -n "${value}" ] || value='0'
  echo "${value}"
}

# Rewrites the whole marker file: header, then the three known keys in a fixed
# order, then any other key=value line the file already had. The fixed order is
# what makes the output byte-identical run to run, and carrying unrecognized
# keys through means an older init.sh cannot drop a key a newer one added and
# start the diffs oscillating all over again.
function write_markers () {
  local file=$1
  local lfs=$2
  local meta=$3
  local self=$4
  local tmp="${file}.tmp"

  {
    printf '%s\n' "${MANAGED_BY}"
    printf '%s\n' '# Each key records the tool that generated the matching part. A part is only'
    printf '%s\n' '# regenerated by a machine whose copy of that tool is newer than the value here.'
    printf '%s=%s\n' "${KEY_LFS}" "${lfs}"
    printf '%s=%s\n' "${KEY_META}" "${meta}"
    printf '%s=%s\n' "${KEY_SELF}" "${self}"
    if [ -f "${file}" ]; then
      grep -Ev "^[[:space:]]*#|^[[:space:]]*\$|^(${KEY_LFS}|${KEY_META}|${KEY_SELF})=" "${file}" || :
    fi
  } > "${tmp}" || return 1

  mv "${tmp}" "${file}" || return 1
}

# Digs the version out of `git lfs version`, which prints something like
#
#   git-lfs/3.7.0 (GitHub; darwin arm64; go 1.24.4)
#
# The parenthesized build details differ between Homebrew and MacPorts builds,
# so the match is anchored on the git-lfs/ prefix. A bare "first digits on the
# line" match would happily come back with the *Go* version instead. Takes the
# string rather than running the command, so the tests can drive it.
#
# Echoes nothing when the format is unrecognized; the caller then warns and
# skips regeneration rather than rewriting the committed hooks on a guess.
function parse_lfs_version () {
  printf '%s\n' "$1" | perl -ne 'if (m{git-lfs/([0-9]+(?:\.[0-9]+)+)}) { print "$1\n"; exit }'
}

# Identifies the local git-store-meta as <upstream version>+sha256.<12 hex>.
#
# The pinned TAG_COMMIT lives in bootstrap.sh, not here, and neither a commit
# bump within the same upstream tag nor a change to dst-hack.patch moves
# --version -- so a digest of the file itself is what actually tracks the tool.
# It is labelled sha256. so that nobody reads it as a git commit. Compared for
# equality and never ordered, because a hash has no ordering.
#
# Echoes nothing if the script cannot be run or hashed, which the caller treats
# the same way as an unparsable git-lfs version.
function store_meta_version () {
  local pl=$1
  local version digest

  [ -x "${pl}" ] || return 0
  version="$("${pl}" --version 2>/dev/null | head -1)"
  digest="$(shasum -a256 "${pl}" 2>/dev/null | cut -c1-12)"
  [ -n "${version}" ] || return 0
  [ -n "${digest}" ] || return 0
  echo "${version}+sha256.${digest}"
}

# True when at least one <hook>.d folder already holds the named part. A marker
# that is up to date but whose parts have been deleted would otherwise leave the
# repo permanently without hooks, so a missing part always forces regeneration.
function parts_present () {
  local hooks_dir=$1
  local part_name=$2
  local part_dir

  for part_dir in "${hooks_dir}"/*.d; do
    [ -f "${part_dir}/${part_name}" ] && return 0
  done
  return 1
}

function init_repo () {
  # Initialize Git
  git init
}

function init_lfs () {
  # Initialize Git LFS.
  #
  # --skip-repo: this only has to write the global clean/smudge/process filter
  # config. Hooks are bootstrap_hooks' job, and this runs first -- so hooks
  # written here would land in the staging folder and then be swept off into
  # .githooks/pre-migration/*.staging as "somebody else's", leaving spurious
  # backup files behind on every brand-new repo.
  git lfs install --skip-repo || warn "\`git lfs install --skip-repo\` failed; the global LFS filters may not be configured."
  for t in "${LFS_TYPES[@]}"; do
    git lfs track "$t"
  done
}

# Where both generators are made to write, before their output is harvested
# into .githooks. NOT `git rev-parse --git-path hooks`, which resolves through
# core.hooksPath and would answer ".githooks" on a re-run. This matches what
# git-store-meta uses internally for --install.
function staging_hooks_dir () {
  echo "$(git rev-parse --git-dir)/hooks"
}

# Copies each pre-dispatcher merged hook to .githooks/pre-migration/ before it
# is regenerated. The generated halves are recreated from scratch anyway; the
# copy exists only so that anything hand-edited into the merged file is
# recoverable rather than lost. A hook that already has a .d folder is
# dispatcher-era and is left alone.
function migrate_legacy_hooks () {
  local hooks_dir=$1
  local migration_dir="${hooks_dir}/${MIGRATION_DIR}"
  local hook_path hook

  for hook_path in "${hooks_dir}"/*; do
    # skips the .d folders and pre-migration itself, which are not files
    [ -f "${hook_path}" ] || continue
    hook="$(basename "${hook_path}")"
    # everything else in here (git-store-meta.pl, its checksum) is inert: Git
    # only executes files whose name matches a hook exactly
    case "${hook}" in
      pre-*|post-*|commit-msg|prepare-commit-msg) ;;
      *) continue ;;
    esac
    [ -d "${hook_path}.d" ] && continue

    mkdir -p "${migration_dir}" || return 1
    warn "Backing up merged ${hook} hook to ${migration_dir}/"
    cp "${hook_path}" "${migration_dir}/${hook}" || return 1
  done
}

# Empties the staging folder so that whatever a generator leaves behind is
# unambiguously that generator's output. Samples are Git's own boilerplate and
# are simply removed; anything else is somebody's hook, so it is set aside
# rather than deleted.
function clear_staging_hooks () {
  local staging_dir=$1
  local hooks_dir=$2
  local migration_dir="${hooks_dir}/${MIGRATION_DIR}"
  local hook_path hook

  [ -d "${staging_dir}" ] || return 0
  rm -f "${staging_dir}"/*.sample

  for hook_path in "${staging_dir}"/*; do
    [ -f "${hook_path}" ] || continue
    hook="$(basename "${hook_path}")"
    mkdir -p "${migration_dir}" || return 1
    warn "Moving unexpected ${hook_path} to ${migration_dir}/${hook}.staging"
    mv "${hook_path}" "${migration_dir}/${hook}.staging" || return 1
  done
}

# Drops one named part from every .d folder, so that a hook a tool no longer
# generates does not keep a stale part around.
function remove_parts () {
  local hooks_dir=$1
  local part_name=$2
  local part_dir

  for part_dir in "${hooks_dir}"/*.d; do
    [ -d "${part_dir}" ] || continue
    rm -f "${part_dir}/${part_name}"
  done
}

# Copies a generated hook, inserting the ownership comment just after the
# shebang, so that a file clobbered by something else -- `git lfs install
# --force` rewrites the committed hooks with raw templates -- is recognizable as
# having been ours. awk rather than `sed '1a\'`, whose continuation syntax
# differs between the BSD sed on Mac OS X and the GNU sed on CI.
function stamp_managed_by () {
  local src=$1
  local dst=$2

  awk -v note="${MANAGED_BY}" \
    'NR==1 { print; print note; next } { print }' "${src}" > "${dst}"
}

# Harvests everything Git LFS just wrote into the staging folder. The file name
# *is* the hook name, so the parts can be collected by iterating rather than by
# hardcoding a list -- a hook added by a future git-lfs is picked up for free.
function harvest_lfs_parts () {
  local staging_dir=$1
  local hooks_dir=$2
  local src hook dst
  local found=0

  for src in "${staging_dir}"/*; do
    [ -f "${src}" ] || continue
    hook="$(basename "${src}")"

    # verify the part really was produced before moving it into place
    if ! grep -q 'git.lfs' "${src}"; then
      err "unexpected content in generated ${hook} hook; expected a Git LFS hook"
      return 1
    fi

    dst="${hooks_dir}/${hook}.d/${LFS_PART}"
    mkdir -p "${hooks_dir}/${hook}.d" || return 1
    stamp_managed_by "${src}" "${dst}" || { rm -f "${dst}"; return 1; }
    rm -f "${src}"
    chmod a+x "${dst}" || return 1
    found=$((found+1))
  done

  if [ "${found}" -eq 0 ]; then
    err "Git LFS did not generate any hooks in ${staging_dir}"
    return 1
  fi
}

# Same harvest for Git Store Meta, plus the interpreter-path rewrite.
#
# Each generated hook finds the Perl script relative to itself:
#
#   script=$(dirname "$0")/git-store-meta.pl
#   [ ! -x "$script" ] && script=git-store-meta.pl
#
# That resolved while the hook sat at .githooks/<name>. A part at
# .githooks/<name>.d/<part> is one directory deeper, so it misses, and the
# fallback is a bare PATH lookup that misses too: pre-commit would exit 1
# (loud) but post-checkout and post-merge would exit 127, which Git ignores --
# timestamps would quietly stop being restored and Logic would resume
# recalculating overviews, with nothing reported. git-logic-init owns this
# folder hierarchy, so git-logic-init fixes the path.
function harvest_store_meta_parts () {
  local staging_dir=$1
  local hooks_dir=$2
  local src hook dst tmp
  local found=0

  for src in "${staging_dir}"/*; do
    [ -f "${src}" ] || continue
    hook="$(basename "${src}")"
    dst="${hooks_dir}/${hook}.d/${META_PART}"
    tmp="${src}.tmp"

    # `|` as the delimiter because the pattern contains `/`, and a single
    # quoted sed script so $(dirname "$0") stays literal
    sed 's|^script=$(dirname "$0")/git-store-meta\.pl$|script=$(dirname "$0")/../git-store-meta.pl|' \
      "${src}" > "${tmp}"

    # Catches a changed hook format when TAG_COMMIT is bumped, rather than
    # shipping broken parts -- git-store-meta v2.1.2, for one, passes the
    # filename through escapeshellarg and so emits it in quotes. Writing to
    # $tmp first matters: `>` truncates before sed runs, so failing straight
    # into $dst would leave a zero-byte part that the dispatcher silently
    # skips as non-executable.
    if ! grep -qF 'script=$(dirname "$0")/../git-store-meta.pl' "${tmp}"; then
      err "git-store-meta hook format changed; interpreter path not rewritten in ${hook}"
      rm -f "${tmp}"
      return 1
    fi

    mkdir -p "${hooks_dir}/${hook}.d" || return 1
    stamp_managed_by "${tmp}" "${dst}" || { rm -f "${tmp}"; return 1; }
    rm -f "${tmp}" "${src}"
    chmod a+x "${dst}" || return 1
    found=$((found+1))
  done

  if [ "${found}" -eq 0 ]; then
    err "Git Store Meta did not generate any hooks in ${staging_dir}"
    return 1
  fi
}

# Writes the dispatcher for one hook. The output is byte-identical every run --
# no timestamps, no version strings -- so re-running init.sh leaves git status
# clean.
function write_dispatcher () {
  local hooks_dir=$1
  local hook=$2
  local part_dir="${hooks_dir}/${hook}.d"
  local dispatcher="${hooks_dir}/${hook}"
  local abort_on_error=0
  local stdin_sensitive=0
  local n_parts=0
  local part

  # A failing pre-* hook should block the operation, so stop at the first
  # non-zero. Git ignores the exit status of post-* hooks entirely, so
  # aborting there would only skip the remaining parts for no benefit.
  case "${hook}" in
    pre-*) abort_on_error=1 ;;
  esac

  # stdin is a stream: the first part to read it consumes it. Only these hooks
  # receive anything on stdin, and today each has a single part, so no
  # buffering is needed -- but a second part would otherwise see EOF and
  # silently do nothing, so refuse instead. post-rewrite is the plausible
  # future addition: client-side, reads stdin, fires after amend and rebase.
  case "${hook}" in
    pre-push|post-rewrite) stdin_sensitive=1 ;;
  esac

  if [ "${stdin_sensitive}" -eq 1 ]; then
    for part in "${part_dir}"/*; do
      [ -x "${part}" ] || continue
      n_parts=$((n_parts+1))
    done
    if [ "${n_parts}" -gt 1 ]; then
      err "${hook}: multiple parts require stdin buffering, which this dispatcher does not implement"
      return 1
    fi
  fi

  # The header below carries the only substituted values; the body after it is
  # copied out verbatim, so $hook and friends there resolve at hook run time.
  {
    cat <<EOF
#!/bin/sh
# Generated by git-logic-init -- do not edit.
hook=${hook}
abort_on_error=${abort_on_error}
stdin_sensitive=${stdin_sensitive}
EOF
    cat <<'EOF'

# Runs every executable part in <hook>.d, in sort order. Parts are named
# NN-<tool>; the number is sort order, not priority. Parts named 10- and 20-
# are regenerated by init.sh -- anything you add yourself is never touched.

dir=$(dirname "$0")/$hook.d
[ -d "$dir" ] || exit 0

# Non-executable files are skipped, which covers most editor leftovers -- but
# a backup of an executable part keeps its mode, so name those out explicitly.
is_part () {
    [ -x "$1" ] || return 1
    case "$1" in
        *~|*.bak|*.orig|*.rej) return 1 ;;
    esac
    return 0
}

if [ "$stdin_sensitive" -eq 1 ]; then
    n_parts=0
    for part in "$dir"/*; do
        is_part "$part" || continue
        n_parts=$((n_parts+1))
    done
    if [ "$n_parts" -gt 1 ]; then
        printf >&2 '%s\n' "$hook: multiple parts require stdin buffering, which this dispatcher does not implement"
        exit 1
    fi
fi

status=0
for part in "$dir"/*; do
    is_part "$part" || continue
    "$part" "$@" || {
        rc=$?
        # name the part, otherwise a failing hook means hunting for which one
        printf >&2 '%s\n' "$hook: part $(basename "$part") exited $rc"
        [ "$abort_on_error" -eq 1 ] && exit $rc
        status=$rc
    }
done
exit $status
EOF
  } > "${dispatcher}" || return 1

  chmod a+x "${dispatcher}" || return 1
}

# One dispatcher per .d folder, so a hook only exists if something generates
# parts for it.
function write_dispatchers () {
  local hooks_dir=$1
  local part_dir hook

  for part_dir in "${hooks_dir}"/*.d; do
    [ -d "${part_dir}" ] || continue
    hook="$(basename "${part_dir}" .d)"
    write_dispatcher "${hooks_dir}" "${hook}" || return 1
  done
}

function bootstrap_hooks () {

  # Preserve file timestamps of Audio Files. Otherwise Logic
  # will re-calculate waveforms after checkout and change
  # the checksums!! Special thanks to:
  # https://github.com/danny0838/git-store-meta
  #
  # Both tools generate whole hook files, so each is run in turn against an
  # empty staging folder and its output harvested into its own part. Nothing
  # is merged, so nothing has to be guessed at -- and the two can then be
  # updated independently.
  #
  # The generated files are byte-exact copies of what each tool emits, so they
  # change whenever a contributor's copy of that tool differs from the one that
  # last wrote them -- which used to show up as an unexplained working-tree diff
  # after a git-lfs upgrade. Each part is therefore only regenerated when the
  # local tool is newer than the version recorded in .githooks/VERSIONS. That
  # makes regeneration monotonic: the newest machine's output propagates to
  # everyone through an ordinary commit, and older machines leave it alone. See
  # issue #20.

  local staging_dir versions_file
  local local_lfs local_meta marker_lfs marker_meta
  local lfs_regen=0 meta_regen=0

  staging_dir="$(staging_hooks_dir)"
  versions_file="${NEW_HOOKS_DIR}/${VERSIONS_FILE}"

  marker_lfs="$(read_marker "${versions_file}" "${KEY_LFS}")"
  marker_meta="$(read_marker "${versions_file}" "${KEY_META}")"
  local_lfs="$(parse_lfs_version "$(git lfs version 2>/dev/null)")"
  local_meta="$(store_meta_version "${NEW_HOOKS_DIR}/git-store-meta.pl")"

  # Ordered comparison: only a strictly newer git-lfs rewrites the part. An
  # unparsable version regenerates nothing rather than guessing.
  if [ -z "${local_lfs}" ]; then
    warn "Could not read a version out of \`git lfs version\`; leaving the ${LFS_PART} parts alone."
  elif [ "$(compareVersions "${local_lfs}" "${marker_lfs}")" -eq 1 ]; then
    lfs_regen=1
  elif ! parts_present "${NEW_HOOKS_DIR}" "${LFS_PART}"; then
    lfs_regen=1
  fi

  # Equality, not ordering: the git-store-meta identity ends in a hash, and a
  # hash cannot be ordered. Safe here because the value only moves when a
  # maintainer bumps the pin in bootstrap.sh and cuts a release.
  if [ -z "${local_meta}" ]; then
    warn "Could not identify the local git-store-meta; leaving the ${META_PART} parts alone."
  elif [ "${local_meta}" != "${marker_meta}" ]; then
    meta_regen=1
  elif ! parts_present "${NEW_HOOKS_DIR}" "${META_PART}"; then
    meta_regen=1
  fi

  # Always, and before anything else: write_dispatchers below overwrites
  # .githooks/<hook>, so a legacy merged hook has to be set aside even on a run
  # that regenerates no parts at all.
  migrate_legacy_hooks "${NEW_HOOKS_DIR}" || return 1

  # Only when something is actually about to be generated -- this relocates
  # unexpected staged hooks into pre-migration/, which should not happen on a
  # run that generates nothing.
  if [ "${lfs_regen}" -eq 1 ] || [ "${meta_regen}" -eq 1 ]; then
    clear_staging_hooks "${staging_dir}" "${NEW_HOOKS_DIR}" || return 1
  fi

  if [ "${lfs_regen}" -eq 1 ]; then
    info "Initializing Git LFS hooks (${local_lfs})"
    # creates git hooks for: pre-push, post-checkout, post-commit, post-merge.
    # A hook added by a future git-lfs is harvested for free, which is the main
    # advantage over pinning the hook text here.
    remove_parts "${NEW_HOOKS_DIR}" "${LFS_PART}"
    git -c core.hooksPath="${staging_dir}" lfs install || return 1
    harvest_lfs_parts "${staging_dir}" "${NEW_HOOKS_DIR}" || return 1
    marker_lfs="${local_lfs}"
  else
    info "Git LFS hooks are already at ${marker_lfs}; leaving them alone"
    # --skip-repo still writes the global clean/smudge/process filter config,
    # which a freshly set-up machine needs even when its hooks are older than
    # the committed ones. Only a warning if the flag is missing: an ancient
    # git-lfs should degrade to a no-op, not abort the whole run.
    git lfs install --skip-repo || warn "\`git lfs install --skip-repo\` failed; the global LFS filters may not be configured."
  fi

  if [ "${meta_regen}" -eq 1 ]; then
    info "Initializing Git Store Meta hooks (${local_meta})"
    # creates git hooks for: pre-commit, post-checkout and post-merge.
    # --force because the staging folder is emptied above, rather than having
    # the existing hooks shuffled out of the way one at a time first.
    remove_parts "${NEW_HOOKS_DIR}" "${META_PART}"
    "${NEW_HOOKS_DIR}"/git-store-meta.pl --install --force || return 1
    harvest_store_meta_parts "${staging_dir}" "${NEW_HOOKS_DIR}" || return 1
    marker_meta="${local_meta}"
  else
    info "Git Store Meta hooks are already at ${marker_meta}; leaving them alone"
  fi

  # Unconditional: the dispatcher is byte-identical for a given git-logic-init
  # version, so re-running costs nothing -- and running it every time is what
  # gives a .d folder newly created by a newer git-lfs its dispatcher for free.
  write_dispatchers "${NEW_HOOKS_DIR}" || return 1

  write_markers "${versions_file}" "${marker_lfs}" "${marker_meta}" "${RELEASE_VERSION}" || return 1
}

# -----------------------------------------------------------------------------

# Unit tests source this script to exercise the functions above. The sentinel
# below stops before any side effects. See test/compare-versions.sh.t
if [ -n "${SOURCE_FUNCTIONS_ONLY}" ]; then
  return 0
fi

# Check for binaries

PKG_MANAGER="$(detect_pkg_manager)"

if [ -z "${PKG_MANAGER}" ]; then
  warn "WARNING: neither Homebrew nor MacPorts was found!"
  warn "Installing one of them is highly recommended."
fi

if ! [ -x "$(command -v git)" ]; then
  err 'Git is not installed. Use `brew install git` or `sudo port install git` to install.'
  exit 1
fi

# check minimum version for git config core.hooksPath
git_version=`git --version | perl -pe '($_)=/([0-9]+([.][0-9]+)+)/'`
if [ "$(compareVersions "$MIN_GIT_VERSION" "$git_version")" -eq 1 ] ; then
  err "Git version $git_version must be >= $MIN_GIT_VERSION. Use \`brew upgrade git\` or \`sudo port selfupdate && sudo port upgrade git\` to upgrade."
  exit 1
fi

if ! [ -x "$(command -v git-lfs)" ]; then
  err 'Git LFS is not installed. Use `brew install git-lfs` or `sudo port install git-lfs` to install.'
  exit 1
fi

# Refuse to run an init.sh older than the one that wrote this repo's hooks --
# it would regenerate the dispatchers from an older template and rewrite the
# marker downward, which is exactly the oscillating diff this design removes.
# Checked here, before .gitignore or .githooks is touched, so that a stale
# script changes nothing on its way out.
#
# init.sh is committed alongside .githooks in a Logic repo, so the script and
# the marker arrive in the same commit and this should never fire in normal
# use. It fires when someone drops a newer init.sh into the working tree and
# runs it before committing, or has local edits git pull cannot fast-forward.
marker_self="$(read_marker "${NEW_HOOKS_DIR}/${VERSIONS_FILE}" "${KEY_SELF}")"
if [ "$(compareVersions "${RELEASE_VERSION#v}" "${marker_self#v}")" -eq -1 ]; then
  err "This repo's hooks were written by git-logic-init ${marker_self}, but this init.sh is ${RELEASE_VERSION}."
  err 'Run `git pull` to pick up the newer init.sh, then run `bash init.sh` again.'
  err 'If init.sh is untracked or locally modified, Git cannot update it -- replace it from GitHub Releases.'
  exit 1
fi

if ! [ -d "${NEW_HOOKS_DIR}" ]; then
  mkdir "${NEW_HOOKS_DIR}"
fi

if ! [ -f "${NEW_HOOKS_DIR}/git-store-meta.pl" ]; then
  info "Git Store Meta not found, downloading..."
  curl -s -L -OO "${RELEASE_BASEURL}/${RELEASE_VERSION}/git-store-meta{.pl,.pl.sha256}"
  shasum -a256 -c git-store-meta.pl.sha256
  if [ $? -ne 0 ]; then
    err "Error"
    exit 1
  fi
  mv "git-store-meta.pl" "${NEW_HOOKS_DIR}/git-store-meta.pl"
  mv "git-store-meta.pl.sha256" "${NEW_HOOKS_DIR}"
fi

# make sure local hook is executable, if exists
if [ -f "${NEW_HOOKS_DIR}/git-store-meta.pl" ]; then
  chmod a+x "${NEW_HOOKS_DIR}/git-store-meta.pl"
fi

# Check ignore rules. Assume owner of repo has access to all plugins so
# that Freeze Files are not needed. Otherwise, manually zip up the Freeze Files
# folder if needed to the archive
touch .gitignore
for g in "${GIT_IGNORE[@]}"; do
  # Special thanks to:
  # https://stackoverflow.com/a/3557165/1603489
  grep -qxF "$g" .gitignore || echo "$g" >> .gitignore
done

if [ "$(git diff --name-only .gitignore | wc -l)" -gt 0 ]; then
  info "Changes successfully made to .gitignore"
  err "Please commit changes first and then re-run init.sh again"
  exit
fi

if ! [ -d "./.git" ]; then
  init_repo
fi

if ! [ -f ".gitattributes" ]; then
  init_lfs
elif ! grep -q "lfs" ".gitattributes"; then
  init_lfs
fi

# check if repo has a remote, pull LFS files
git rev-parse --abbrev-ref --symbolic-full-name @{u} >/dev/null 2>&1
if [ $? -eq 0 ]; then
  git lfs pull
fi

# An ignored marker would read as "0" on every fresh clone, so every clone would
# regenerate and commit the hooks again -- the exact churn this file prevents.
if git check-ignore -q "${NEW_HOOKS_DIR}/${VERSIONS_FILE}" 2>/dev/null; then
  warn "${NEW_HOOKS_DIR}/${VERSIONS_FILE} is matched by a .gitignore rule."
  warn "It has to be committed, or the hooks will be regenerated on every clone."
fi

# Which parts actually get regenerated is decided inside, per tool, against
# .githooks/VERSIONS -- so this is safe to run every time.
if ! bootstrap_hooks; then
  err "Error setting up commit hooks"
  exit 1
fi

# enable pre-commit hook
touch .git_store_meta

# initialize hooks location (must be done after each clone)
git config core.hooksPath "${NEW_HOOKS_DIR}"
info "git config core.hooksPath [${NEW_HOOKS_DIR}] successfully initialized"

# apply changes for fresh clones
if [ -s .git_store_meta ]
then
   ./"${NEW_HOOKS_DIR}/git-store-meta.pl" --apply
else
   # configure empty file
   ./"${NEW_HOOKS_DIR}/git-store-meta.pl" --store -f "${GIT_META_FIELDS}"
fi
if [ $? -ne 0 ]; then
  err "Error"
  exit 1
fi

info "Cheers!"
