on:
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test.yml

  release:
    needs: test
    name: prepare draft release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Patch DST
      # Downloads the vanilla Git Store Meta source (from a fork, for backup) and applies the DST patch needed for Logic X
        run: "${{ github.workspace }}/scripts/bootstrap.sh"
      - name: Generate Checksums
        run: |
          cd ${{ github.workspace }}/scripts
          sha256sum "init.sh" > "init.sh.sha256"
          sha256sum "git-store-meta.pl" > "git-store-meta.pl.sha256"
      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            scripts/init.sh
            scripts/init.sh.sha256
            scripts/git-store-meta.pl
            scripts/git-store-meta.pl.sha256
          draft: true