name: test
on:
  pull_request:
  push:
    branches: [ master ]
  workflow_dispatch:
  workflow_call:          # lets main.yml invoke this same definition

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Patch DST
      # Downloads the vanilla Git Store Meta source (from a fork, for backup) and applies the DST patch needed for Logic X
        run: "${{ github.workspace }}/scripts/bootstrap.sh"
      - name: Test Compile
        run: "${{ github.workspace }}/test/download.sh"
      - name: Test Verify
        run: |
          cd ${{ github.workspace }}/test
          PERL5LIB=${{ github.workspace }}/test perl dst-hack.t
      - name: Shellcheck
        run: shellcheck scripts/*.sh